### ISSUE TITLE
Update Lua to 5.3.1

### ISSUE THREAD

**Issue by xboi209** [pvpgn/pvpgn-magic-builder#13]
http://www.lua.org/download.html

**Comment by HarpyWar** [comment]
Lua updated from 5.1.4 -> 5.1.5.

It can't be easy updated to 5.3.x because Lua is connected to PvPGN with a library http://luasp.org/ that uses Lua 5.1.x interface. Actually it's possible, but It may take a time to find a solution.
Btw, Lua 5.1 is most popular now. I don't know why but I think because there are more tools for 5.1 than 5.3.
