### ISSUE TITLE
Why binary files in main tree?

### ISSUE THREAD

**Issue by stas730** [pvpgn/pvpgn-magic-builder#20]
Where is source code of executable files?
What is bnhash.exe and choice.exe? Wget.exe is trusted (I know, where is code).

**Comment by stas730** [comment]
Executable*

**Comment by stas730** [comment]
*Executable

**Comment by HarpyWar** [comment]
Download the latest package from [Release](https://github.com/pvpgn/pvpgn-magic-builder/releases) section
Run `pvpgn.bat` or `d2gs.bat` depending on what you need to build.

**Comment by stas730** [comment]
But why binary files in main tree?

**Comment by stas730** [comment]
What is bnhash.exe and choice.exe? Wget.exe is trusted (I know, where is code).

**Comment by HarpyWar** [comment]
Well, most of the binaries are 3d-party utilities which purpose is to extend the batch script language:

`bnhash.exe` is renamed `bnpass` https://github.com/pvpgn/pvpgn-server/tree/master/src/bnpass
`choice.exe` is default Windows utility that I've downloaded from the Microsoft web site as a part of Windows 98 Reskit. I add it because it not exists in several Windows editions https://technet.microsoft.com/en-us/library/cc732504%28v=ws.11%29.aspx?f=255&MSPPError=-2147217396 (``choice.exe /?`` for help, the file can be replaced by yours `%windir%/system32/choice.exe` if you have it)
`unzip.exe` http://gnuwin32.sourceforge.net/packages/unzip.htm
`md5sum.exe` was taken from http://www.etree.org/md5com.html (`md5sum.exe --help` for help and credits)

**Comment by HarpyWar** [comment]
All third-party programs that used for Magic Builder work were excluded from the repository and downloaded from trusted locations on demand.
