### ISSUE TITLE
Error Visual C++ is Not Installed

### ISSUE THREAD

**Issue by raumuongluoc** [pvpgn/pvpgn-magic-builder#40]
I have installed visual studio 2017, but when running build_pvpgn it doesn't recognize visual studio 2017, why is that
![Untitled](https://user-images.githubusercontent.com/16100494/93725835-67bc6c00-fbdc-11ea-8ec7-3d6c4b8b7931.png)

**Comment by HarpyWar** [comment]
I can't reproduce the issue on fresh installation Windows 10 and VC++ 2017.

If it does not help show output from the following two commands:
```
module\tools\vswhere.exe
module\tools\vswhere.exe -products * -requires Microsoft.Component.MSBuild -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
```
And check does file `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat` exist or not.

**Comment by Happin3ss** [comment]
In case other ppl might get the same issue. The root cause is that your VS need to install C++ build tool as well to be able to use magic builder. The below picture will help:
![image](https://user-images.githubusercontent.com/17236895/108889184-aa2c1e00-763e-11eb-96f1-6ac17b54101a.png)
@HarpyWar can you please update the readme with that ? Thanks a lot
